services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: futurex_user
      POSTGRES_PASSWORD: futurex_secret_2025
      POSTGRES_DB: invoice_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
